Update ISO setup (remove keyboard, ...) change omarchy to airchy

diff --git a/configs/airootfs/root/configurator b/configs/airootfs/root/configurator
--- a/configs/airootfs/root/configurator
+++ b/configs/airootfs/root/configurator
@@ -29,115 +29,124 @@ notice() {
 
 # STEP 1: KEYBOARD LAYOUT
 
-keyboard_form() {
-  step "Let's setup your machine..."
-  keyboards=$'Azerbaijani|azerty
-Belarusian|by
-Belgian|be-latin1
-Bosnian|ba
-Bulgarian|bg-cp1251
-Croatian|croat
-Czech|cz
-Danish|dk-latin1
-Dutch|nl
-English (UK)|uk
-English (US)|us
-English (US, Dvorak)|dvorak
-Estonian|et
-Finnish|fi
-French|fr
-French (Canada)|cf
-French (Switzerland)|fr_CH
-Georgian|ge
-German|de
-German (Switzerland)|de_CH-latin1
-Greek|gr
-Hebrew|il
-Hungarian|hu
-Icelandic|is-latin1
-Irish|ie
-Italian|it
-Japanese|jp106
-Kazakh|kazakh
-Khmer (Cambodia)|khmer
-Kyrgyz|kyrgyz
-Lao|la-latin1
-Latvian|lv
-Lithuanian|lt
-Macedonian|mk-utf
-Norwegian|no-latin1
-Polish|pl
-Portuguese|pt-latin1
-Portuguese (Brazil)|br-abnt2
-Romanian|ro
-Russian|ru
-Serbian|sr-latin
-Slovak|sk-qwertz
-Slovenian|slovene
-Spanish|es
-Spanish (Latin American)|la-latin1
-Swedish|sv-latin1
-Tajik|tj_alt-UTF8
-Turkish|trq
-Ukrainian|ua'
-  choice=$(printf '%s\n' "$keyboards" | cut -d'|' -f1 | gum choose --height 10 --selected "English (US)" --header "Select keyboard layout") || abort
-  keyboard=$(printf '%s\n' "$keyboards" | awk -F'|' -v c="$choice" '$1==c{print $2; exit}')
-
-  # Only attempt to load keyboard layout if we're on a real console
-  # loadkeys only works on Linux virtual consoles (tty), not in terminal emulators
-  if [[ $(tty 2>/dev/null) == "/dev/tty"* ]]; then
-    loadkeys "$keyboard" 2>/dev/null
-  fi
-}
-
-keyboard_form
+# keyboard_form() {
+#   step "Let's setup your machine..."
+#   keyboards=$'Azerbaijani|azerty
+# Belarusian|by
+# Belgian|be-latin1
+# Bosnian|ba
+# Bulgarian|bg-cp1251
+# Croatian|croat
+# Czech|cz
+# Danish|dk-latin1
+# Dutch|nl
+# English (UK)|uk
+# English (US)|us
+# English (US, Dvorak)|dvorak
+# Estonian|et
+# Finnish|fi
+# French|fr
+# French (Canada)|cf
+# French (Switzerland)|fr_CH
+# Georgian|ge
+# German|de
+# German (Switzerland)|de_CH-latin1
+# Greek|gr
+# Hebrew|il
+# Hungarian|hu
+# Icelandic|is-latin1
+# Irish|ie
+# Italian|it
+# Japanese|jp106
+# Kazakh|kazakh
+# Khmer (Cambodia)|khmer
+# Kyrgyz|kyrgyz
+# Lao|la-latin1
+# Latvian|lv
+# Lithuanian|lt
+# Macedonian|mk-utf
+# Norwegian|no-latin1
+# Polish|pl
+# Portuguese|pt-latin1
+# Portuguese (Brazil)|br-abnt2
+# Romanian|ro
+# Russian|ru
+# Serbian|sr-latin
+# Slovak|sk-qwertz
+# Slovenian|slovene
+# Spanish|es
+# Spanish (Latin American)|la-latin1
+# Swedish|sv-latin1
+# Tajik|tj_alt-UTF8
+# Turkish|trq
+# Ukrainian|ua'
+#   choice=$(printf '%s\n' "$keyboards" | cut -d'|' -f1 | gum choose --height 10 --selected "English (US)" --header "Select keyboard layout") || abort
+#   keyboard=$(printf '%s\n' "$keyboards" | awk -F'|' -v c="$choice" '$1==c{print $2; exit}')
+#
+#   # Only attempt to load keyboard layout if we're on a real console
+#   # loadkeys only works on Linux virtual consoles (tty), not in terminal emulators
+#   if [[ $(tty 2>/dev/null) == "/dev/tty"* ]]; then
+#     loadkeys "$keyboard" 2>/dev/null
+#   fi
+# }
+#
+# keyboard_form
+# ----
+# Only attempt to load keyboard layout if we're on a real console
+# loadkeys only works on Linux virtual consoles (tty), not in terminal emulators
+if [[ $(tty 2>/dev/null) == "/dev/tty"* ]]; then
+  loadkeys "English (US)|us" 2>/dev/null
+fi
 
 # STEP 2: USER
 
 user_form() {
   step "Let's setup your user account..."
 
-  while true; do
-    username=$(gum input --placeholder "Alphanumeric without spaces (like dhh)" --prompt.foreground="#845DF9" --prompt "Username> ") || abort
+  # while true; do
+  #   username=$(gum input --placeholder "Alphanumeric without spaces (like dhh)" --prompt.foreground="#845DF9" --prompt "Username> ") || abort
+  #
+  #   if [[ "$username" =~ ^[a-z_][a-z0-9_-]*[$]?$ ]]; then
+  #     break
+  #   else
+  #     notice "Username must be alphanumeric with no spaces" 1
+  #   fi
+  # done
+  username="chdai"
 
-    if [[ "$username" =~ ^[a-z_][a-z0-9_-]*[$]?$ ]]; then
-      break
-    else
-      notice "Username must be alphanumeric with no spaces" 1
-    fi
-  done
-
-  while true; do
-    password=$(gum input --placeholder "Used for user + root + encryption" --prompt.foreground="#845DF9" --password --prompt "Password> ") || abort
-    password_confirmation=$(gum input --placeholder "Must match the password you just typed" --prompt.foreground="#845DF9" --password --prompt "Confirm> ") || abort
-
-    if [[ -n "$password" && "$password" == "$password_confirmation" ]]; then
-      break
-    elif [[ -z "$password" ]]; then
-      notice "Your password can't be blank!" 1
-    else
-      notice "Passwords didn't match!" 1
-    fi
-  done
+  # while true; do
+  #   password=$(gum input --placeholder "Used for user + root + encryption" --prompt.foreground="#845DF9" --password --prompt "Password> ") || abort
+  #   password_confirmation=$(gum input --placeholder "Must match the password you just typed" --prompt.foreground="#845DF9" --password --prompt "Confirm> ") || abort
+  #
+  #   if [[ -n "$password" && "$password" == "$password_confirmation" ]]; then
+  #     break
+  #   elif [[ -z "$password" ]]; then
+  #     notice "Your password can't be blank!" 1
+  #   else
+  #     notice "Passwords didn't match!" 1
+  #   fi
+  # done
+  password="01chdai23!." 
 
   # Hash the password using yescrypt
   password_hash=$(openssl passwd -6 "$password")
 
-  full_name=$(gum input --placeholder "Used for git authentication (hit return to skip)" --prompt.foreground="#845DF9" --prompt "Full name> ")
-  email_address=$(gum input --placeholder "Used for git authentication (hit return to skip)" --prompt.foreground="#845DF9" --prompt "Email address> ")
+  # full_name=$(gum input --placeholder "Used for git authentication (hit return to skip)" --prompt.foreground="#845DF9" --prompt "Full name> ")
+  # email_address=$(gum input --placeholder "Used for git authentication (hit return to skip)" --prompt.foreground="#845DF9" --prompt "Email address> ")
 
-  while true; do
-    hostname=$(gum input --placeholder "Alphanumeric without spaces (or return for 'omarchy')" --prompt.foreground="#845DF9" --prompt "Hostname> ")
-
-    if [[ "$hostname" =~ ^[A-Za-z_][A-Za-z0-9_-]*\$?$ ]]; then
-      break
-    elif [[ -z $hostname ]]; then
-      hostname="omarchy"
-      break
-    else
-      notice "Hostname must be alphanumeric using dashes or underscores but no spaces" 1
-    fi
-  done
+  # while true; do
+  #   hostname=$(gum input --placeholder "Alphanumeric without spaces (or return for 'omarchy')" --prompt.foreground="#845DF9" --prompt "Hostname> ")
+  #
+  #   if [[ "$hostname" =~ ^[A-Za-z_][A-Za-z0-9_-]*\$?$ ]]; then
+  #     break
+  #   elif [[ -z $hostname ]]; then
+  #     hostname="omarchy"
+  #     break
+  #   else
+  #     notice "Hostname must be alphanumeric using dashes or underscores but no spaces" 1
+  #   fi
+  # done
+  hostname="chdai"
 
   # Pick timezone
   geo_guessed_timezone=$(tzupdate -p 2>/dev/null)
@@ -151,7 +160,7 @@ user_form() {
 
 user_form
 
-while true; do
+# while true; do
   # Add manual padding since gum table -p doesn't respect padding
   echo -e "Field,Value
 Username,$username
@@ -163,14 +172,14 @@ Timezone,$timezone
 Keyboard,$keyboard" |
     gum table -s "," -p | sed "s/^/${PADDING_LEFT_SPACES}/"
 
-  echo
-  if gum confirm --negative "No, change it" "Does this look right?"; then
-    break
-  else
-    keyboard_form
-    user_form
-  fi
-done
+  # echo
+  # if gum confirm --negative "No, change it" "Does this look right?"; then
+  #   break
+  # else
+  #   keyboard_form
+  #   user_form
+  # fi
+# done
 
 # STEP 3: DISK
 
@@ -251,7 +260,7 @@ cat <<-_EOF_ >user_credentials.json
     "users": [
         {
             "enc_password": $password_hash_escaped,
-            "groups": [],
+            "groups": [wheel],
             "sudo": true,
             "username": $username_escaped
         }
@@ -349,13 +358,6 @@ cat <<-_EOF_ >user_configuration.json
                 "wipe": true
             }
         ],
-        "disk_encryption": {
-            "encryption_type": "luks",
-            "lvm_volumes": [],
-            "iter_time": 2000,
-            "partitions": [ "8c2c2b92-1070-455d-b76a-56263bab24aa" ],
-            "encryption_password": $password_escaped
-        }
     },
     "hostname": "$hostname",
     "kernels": [ "$kernel_choice" ],
